version: "3.2"

services:
  github-actions-slack:
    build: .
    environment:
      - GITHUB_EVENT_PATH=/event.json
      - GITHUB_REF=/refs/heads/master
      - SLACK_WEBHOOK_URL=[REPLACE_WITH_VALID_WEBHOOK_URL]
